name: coverage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout

        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build

      - name: Generate Coverage Reports
        run: dotnet test --collect:"XPlat Code Coverage" -p:RunSettingsFilePath=build/Coverlet.runsettings
        shell: bash

      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.3.8
        with:
          reports: tests/*/TestResults/*/coverage.cobertura.xml
          targetdir: coveragereport
          reporttypes: Html;Badges

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: Coveragereport # Artifact name
          path: coveragereport # Directory containing files to upload
